# Generated by Django 5.0.1 on 2024-02-01 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prod_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categ_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Poduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prod_Name', models.CharField(max_length=50)),
                ('Prod_Image', models.ImageField(upload_to='path')),
                ('Prod_Image_Desc', models.ImageField(blank=True, null=True, upload_to='path')),
                ('Pod_Price', models.IntegerField()),
                ('Pod_Description', models.TextField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.prod_category')),
            ],
        ),
    ]
