# Generated by Django 5.0.1 on 2024-02-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poduct',
            new_name='Product',
        ),
    ]
