# Generated by Django 5.0.1 on 2024-02-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Prod_Image_Desc',
        ),
        migrations.AlterField(
            model_name='order',
            name='Date_Time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
