# Generated by Django 5.0.1 on 2024-02-20 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_order_user_alter_product_prod_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Product_Name',
            new_name='Product_ID',
        ),
    ]
