# Generated by Django 5.0.1 on 2024-02-21 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_prod_image'),
        ('products', '0006_rename_product_name_order_product_id'),
    ]

    operations = [
    ]
