# Generated by Django 5.0.1 on 2024-02-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_merge_20240221_0044'),
        ('products', '0007_merge_20240221_1214'),
    ]

    operations = [
    ]
